[package]
name = "xgboost_lib-sys"
version = "3.0.1"
authors = ["Dave Challis <dave@suicas.net>", "Marco Mengelkoch"]
links = "xgboost"
build = "build.rs"
license = "MIT"
repository = "https://github.com/marcomq/rust-xgboost"
description = "Native bindings to the xgboost library"
readme = "README.md"
edition = "2021"
exclude = [
    "lib/*",
]

[dependencies]
libc = "0.2.172"

[build-dependencies]
bindgen = "0.71"
cmake = "0.1"
dunce = "1.0.5"
reqwest = { version = "0.12.15", features = ["blocking"] }

[features]
default = ["use_prebuilt_xgb"]
use_prebuilt_xgb = []
cuda = []
