name: Macos

on: [push, pull_request]

env:
  CARGO_TERM_COLOR: always

jobs:
  macos:
    name: macos
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive
        
    - name: Install dependencies
      run: brew install libomp

    - name: Build
      run: cargo build --verbose

    - name: Run tests
      run: cargo test --verbose